name: CI

on: [push]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO 13 when Gradle 6.0 is out
        java_version: [1.8, 9, 10, 11, 12]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Configure Gradle
      # Initial gradle configuration, install dependencies, etc
      run: ./gradlew help
    - name: Build project
      run: ./gradlew assemble --stacktrace
    - name: Run tests
      run: ./gradlew test --stacktrace
    - name: Final checks
      run: ./gradlew check --stacktrace
    - name: Upload snapshot (master only)
      run: ./gradlew uploadArchives -PSONATYPE_NEXUS_USERNAME=${{ secrets.SonatypeUsername }} -PSONATYPE_NEXUS_PASSWORD=${{ secrets.SonatypePassword }}
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && matrix.java_version == '1.8'
